# Generated by Django 4.2.6 on 2023-11-16 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Franchise",
            fields=[
                ("franchise_name", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                "verbose_name_plural": "Franchises",
                "ordering": ["franchise_name"],
            },
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                ("league_name", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                "verbose_name_plural": "Leagues",
                "ordering": ["league_name"],
            },
        ),
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                ("player_name", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("profile_link", models.URLField(blank=True, default=None, max_length=300, null=True, unique=True)),
                ("country", models.CharField(blank=True, default=None, max_length=100, null=True)),
                ("player_role", models.CharField(blank=True, default=None, max_length=100, null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                "verbose_name_plural": "Player Profiles",
                "ordering": ["player_name"],
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                ("tournament_name", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                "verbose_name_plural": "Tournaments",
            },
        ),
        migrations.CreateModel(
            name="Fixture",
            fields=[
                ("scorecard_url", models.URLField(max_length=300, primary_key=True, serialize=False)),
                ("match_date", models.DateField()),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "tournament_name",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tournament.tournament"),
                ),
            ],
            options={
                "verbose_name_plural": "Fixtures",
                "ordering": ["match_date"],
            },
        ),
        migrations.CreateModel(
            name="Standing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("points", models.IntegerField()),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "franchise_name",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tournament.franchise"),
                ),
                (
                    "league_name",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tournament.league"),
                ),
                (
                    "tournament_name",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tournament.tournament"),
                ),
            ],
            options={
                "verbose_name_plural": "Standings",
                "ordering": ["points"],
                "unique_together": {("tournament_name", "league_name", "franchise_name")},
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("power_player", models.BooleanField(default=False)),
                ("price", models.IntegerField(default=10)),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "franchise_name",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tournament.franchise"),
                ),
                (
                    "league_name",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tournament.league"),
                ),
                (
                    "player_name",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tournament.playerprofile"),
                ),
                (
                    "tournament_name",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tournament.tournament"),
                ),
            ],
            options={
                "verbose_name_plural": "Players",
                "ordering": ["player_name"],
                "unique_together": {("player_name", "franchise_name", "league_name", "tournament_name")},
            },
        ),
        migrations.CreateModel(
            name="MatchPoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("match_date", models.DateField()),
                ("batting_points", models.IntegerField()),
                ("bowling_points", models.IntegerField()),
                ("fielding_points", models.IntegerField()),
                ("pom_points", models.IntegerField(blank=True, null=True)),
                ("total_points", models.IntegerField()),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "franchise_name",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tournament.franchise"),
                ),
                (
                    "league_name",
                    models.ForeignKey(
                        default="Banaas Premier League",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.league",
                    ),
                ),
                (
                    "player_name",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tournament.playerprofile"),
                ),
                (
                    "tournament_name",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tournament.tournament"),
                ),
            ],
            options={
                "verbose_name_plural": "MatchPoints",
                "ordering": ["match_date", "total_points"],
                "unique_together": {("player_name", "match_date", "league_name")},
            },
        ),
    ]
