# Generated by Django 4.2.6 on 2023-10-31 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="franchise",
            name="league",
            field=models.ForeignKey(
                default="default-league",
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.league",
                to_field="league",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="franchise",
            name="tournament",
            field=models.ForeignKey(
                default="default-tournament",
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.tournament",
                to_field="tournament",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="league",
            name="tournament",
            field=models.ForeignKey(
                default="default-tournament",
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.tournament",
                to_field="tournament",
            ),
            preserve_default=False,
        ),
    ]
