# Generated by Django 4.2.6 on 2023-11-01 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0002_franchise_league_franchise_tournament_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="franchise",
            options={"ordering": ["franchise"], "verbose_name_plural": "Franchises"},
        ),
        migrations.AlterModelOptions(
            name="league",
            options={"ordering": ["league"], "verbose_name_plural": "Leagues"},
        ),
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["player_name"], "verbose_name_plural": "Players"},
        ),
        migrations.AlterModelOptions(
            name="score",
            options={"ordering": ["score"], "verbose_name_plural": "Scores"},
        ),
        migrations.AlterModelOptions(
            name="tournament",
            options={"verbose_name_plural": "Tournaments"},
        ),
    ]
