# Generated by Django 4.2.6 on 2023-11-01 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0004_player_franchise_player_league_player_tournament"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="franchise",
            field=models.ForeignKey(
                db_column="franchise",
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.franchise",
                to_field="franchise",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="league",
            field=models.ForeignKey(
                db_column="league",
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.league",
                to_field="league",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="tournament",
            field=models.ForeignKey(
                db_column="tournament",
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.tournament",
                to_field="tournament",
            ),
        ),
    ]
