# Generated by Django 4.2.6 on 2023-11-10 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0005_alter_player_franchise_alter_player_league_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="franchise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.franchise", to_field="franchise"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.league", to_field="league"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.tournament", to_field="tournament"
            ),
        ),
    ]
