# Generated by Django 4.2.6 on 2023-11-10 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0007_alter_matchpoint_match_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matchpoint",
            options={"ordering": ["match_date", "total_points"], "verbose_name_plural": "Matches"},
        ),
        migrations.AlterUniqueTogether(
            name="matchpoint",
            unique_together={("player_name", "match_date")},
        ),
    ]
