# Generated by Django 4.2.6 on 2023-11-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0008_alter_matchpoint_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="power_player",
        ),
        migrations.AddField(
            model_name="player",
            name="power_player",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
