# Generated by Django 4.2.6 on 2023-11-12 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0009_remove_score_power_player_player_power_player_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchpoint",
            name="tournament",
        ),
        migrations.AddField(
            model_name="matchpoint",
            name="league",
            field=models.ForeignKey(
                default="Banaas Premier League",
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.league",
                to_field="league",
            ),
        ),
    ]
