# Generated by Django 4.2.6 on 2023-11-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0010_remove_matchpoint_tournament_matchpoint_league"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="matchpoint",
            unique_together={("player_name", "match_date", "league")},
        ),
        migrations.AddField(
            model_name="matchpoint",
            name="franchise",
            field=models.ForeignKey(
                default="Ahmdabad Cyanides",
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.franchise",
                to_field="franchise",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="matchpoint",
            name="tournament",
            field=models.ForeignKey(
                default="ODIWC2023",
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.tournament",
                to_field="tournament",
            ),
            preserve_default=False,
        ),
    ]
